pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerImage: 'toggl-board'

steps:
- task: NodeTool@0
  displayName: 'Configure node version'
  inputs:
    versionSpec: '8.x'

- script: |
    cd server
    npm install
    npm test
  displayName: 'Run test suite'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFiles: 'server/junit.xml'
    testRunTitle: 'Test Results'

- script: |
    cd server
    docker login -u $(dockerId) -p $(dockerPassword)
    docker build -f Dockerfile -t $(dockerId)/$(dockerImage) .
  displayName: 'Build docker image'

- script: |
    cd server
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(dockerImage)
  displayName: 'Push docker image'
