pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerImage: 'toggl-board'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: |
    cd server
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  displayName: 'publish test results'
  inputs:
    testResultsFiles: 'junit.xml'
    testRunTitle: 'Test Results'

- script: |
    cd server
    docker build -f Dockerfile -t $(dockerId)/$(dockerImage) .
  displayName: 'docker build'

