pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerImage: 'toggl-board:$(Build.BuildId)'

steps:
- task: NodeTool@0
  displayName: 'configure node version'
  inputs:
    versionSpec: '8.x'

- script: |
    cd server
    npm install
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  displayName: 'publish test results'
  inputs:
    testResultsFiles: 'server/junit.xml'
    testRunTitle: 'Test Results'

- script: |
    cd server
    docker build -f Dockerfile -t $(dockerId)/$(dockerImage) .
  displayName: 'docker build'

- script: |
    cd server
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(dockerImage)
  displayName: 'docker push'
