pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerImage: 'toggl-board'

steps:
- script: npm install

- script: npm test

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'junit.xml'
    testRunTitle: 'Test Results'

- script: docker build -f Dockerfile -t $(dockerId)/$(dockerImage) .
  displayName: 'docker build'

