pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerImage: 'toggl-board'

steps:
- script: |
    npm install
    npm run test -- --ci
    docker build -f Dockerfile -t $(dockerId)/$(dockerImage) .
  displayName: 'docker build'
